# Generated by Django 4.2.6 on 2024-04-03 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='Course',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='Year',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='ElectionCategories',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
