# Generated by Django 4.2.6 on 2024-04-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_speechrecognitionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='speechrecognitionhistory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
