# Generated by Django 4.2.6 on 2024-04-05 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_speechrecognitionhistory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='Course',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='Year',
        ),
        migrations.RemoveField(
            model_name='speechrecognitionhistory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='speechrecognitionhistory',
            name='microphone_no',
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='Years',
        ),
    ]
