# Generated by Django 4.2.6 on 2024-04-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_remove_myuser_course_remove_myuser_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speechrecognitionhistory',
            name='speech_files',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
